######################################################################
# 
#  File        :  $Source: /cvsroot/ijbswa/current/user.action,v $
# 
#  $Id: user.action,v 1.13 2011/11/06 11:36:01 fabiankeil Exp $
#
#  Purpose     :  User-maintained actions file, see
#                 http://www.privoxy.org/user-manual/actions-file.html
#
######################################################################

# This is the place to add your personal exceptions and additions to
# the general policies as defined in default.action. (Here they will be
# safe from updates to default.action.) Later defined actions always
# take precedence, so anything defined here should have the last word.

# See http://www.privoxy.org/user-manual/actions-file.html, or the 
# comments in default.action, for an explanation of what an "action" is
# and what each action does.

# The examples included here either use bogus sites, or have the actual
# rules commented out (with the '#' character). Useful aliases are
# included in the top section as a convenience.

#############################################################################
# Aliases
#############################################################################
{{alias}}
#############################################################################
#
# You can define a short form for a list of permissions - e.g., instead
# of "-crunch-incoming-cookies -crunch-outgoing-cookies -filter -fast-redirects",
# you can just write "shop". This is called an alias.
#
# Currently, an alias can contain any character except space, tab, '=', '{'
# or '}'.
# But please use only 'a'-'z', '0'-'9', '+', and '-'.
#
# Alias names are not case sensitive.
#
# Aliases beginning with '+' or '-' may be used for system action names 
# in future releases - so try to avoid alias names like this.  (e.g. 
# "+crunch-all-cookies" below is not a good name)
#
# Aliases must be defined before they are used.
# 
# These aliases just save typing later:
#
+crunch-all-cookies = +crunch-incoming-cookies +crunch-outgoing-cookies
-crunch-all-cookies = -crunch-incoming-cookies -crunch-outgoing-cookies
 allow-all-cookies  = -crunch-all-cookies -session-cookies-only -filter{content-cookies}
 allow-popups       = -filter{all-popups} -filter{unsolicited-popups}
+block-as-image     = +block{Blocked image request.} +handle-as-image
-block-as-image     = -block

# These aliases define combinations of actions
# that are useful for certain types of sites:
#
fragile     = -block -crunch-all-cookies -filter -fast-redirects -hide-referer -prevent-compression
shop        = -crunch-all-cookies allow-popups

# Your favourite blend of filters:
#
myfilters   = +filter{html-annoyances} +filter{js-annoyances} +filter{all-popups}\
              +filter{webbugs} +filter{banners-by-size}

# Allow ads for selected useful free sites:
#
allow-ads   = -block -filter{banners-by-size} -filter{banners-by-link}
{+forward-override{forward-socks5 127.0.0.1:8998 .} \
}
setup.office.com
.deviantart.com
.bloomberg.com
.netdna-cdn.com
.youtube-nocookie.com
.wikiquote.org
.nytimes.com
plugins.jetbrains.com
.fastly.net
.vimeo.com
.medium.com
.fbcdn.net
.dropboxusercontent.com
.googlevideo.com
.ytimg.com
.appspot.com
.ggpht.com
.steamstatic.com
/.*(?-i)FORCE_SS.*
.google.
.gmail.com
.google-analytics.com
.googleapis.com
.googlecode.com
.googleusercontent.com
.gstatic.com
goo.gl
.opensuse.org
angular.io
.blogblog.com
.blogger.com
.blogspot.
.wordpress.com
.wp.com
.gravatar.com
.github.io
atom.io
.twimg.com
.sass-lang.com
.cloudup.com
.angularjs.org
.myfonts.net
.cloudflare.com
.curlbuilder.com
.githubapp.com
.githubusercontent.com
gist.github.com
.travis-ci.org
.kali.org
.jwpcdn.com
.sstatic.net
.askubuntu.com
.imgur.com
wiki.archlinux.org
.deviantart.net
.500px.org
.filepicker.io
.balsamiq.com
.msecnd.net
.jetbrains.com
.s3.amazonaws.com
.amazonwebservices.com
blog.jetbrains.com
t.co
.dropbox.com
.twitter.com
.haproxy.org
.live.com
.facebook.net
.optimizely.com
.sourceforge.net
.facebook.com
.jazz.net
.bluemix.net
.mybluemix.net
.gulpjs.com
.npmjs.org
.html5rocks.com
.apple.com
.youtube.com
.nodejs.org
.cloudfront.net
.amazon.com
.ssl-images-amazon.com
.awsstatic.com
.npmjs.com
.mozilla.net
.mozilla.org
.persona.org
.browserscope.org
.chrome.com
.chromium.org
.wikimedia.org
.wikipedia.org
.gravatar.com
{}
assets-cdn.github.com
.google.com.
.gmail.com
.google-analytics.com
.googleapis.com
.googlecode.com
.googleusercontent.com
.gstatic.com
goo.gl
developer.android.com
github.com
#/
# Enable the following section (not the regression-test directives)
# to rewrite and redirect click-tracking URLs on news.google.com.
# Disabling JavaScript should work as well and probably works more reliably.
#
# Redirected URL = http://news.google.com/news/url?ct2=us%2F0_0_s_1_1_a&sa=t&usg=AFQjCNHJWPc7ffoSXPSqBRz55jDA0KgxOQ&cid=8797762374160&url=http%3A%2F%2Fonline.wsj.com%2Farticle%2FSB10001424052970204485304576640791304008536.html&ei=YcqeTsymCIjxggf8uQE&rt=HOMEPAGE&vm=STANDARD&bvm=section&did=-6537064229385238098
# Redirect Destination = http://online.wsj.com/article/SB10001424052970204485304576640791304008536.html
# Ignore = Yes
#
#{+fast-redirects{check-decoded-url}}
#news.google.com/news/url.*&url=http.*&
# Enable the following section (not the regression-test directives)
# to block various Facebook "like" and similar tracking URLs.  At the
# time this section was added it was reported to not break Facebook
# itself but this may have changed by the time you read this. This URL
# list is probably incomplete and if you don't have an account anyway,
# you may prefer to block the whole domain.
#
# Blocked URL = http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Ffacebook.com%2Farstechnica&width=300&colorscheme=light&show_faces=false&stream=false&header=false&height=62&border_color=%23FFFFFF
# Ignore = Yes
# Blocked URL = http://www.facebook.com/plugins/activity.php?site=arstechnica.com&width=300&height=370&header=false&colorscheme=light&recommendations=false&border_color=%23FFFFFF
# Ignore = Yes
# Blocked URL = http://www.facebook.com/plugins/fan.php?api_key=368513495882&connections=10&height=250&id=8304333127&locale=en_US&sdk=joey&stream=false&width=377
# Ignore = Yes
# Blocked URL = http://www.facebook.com/plugins/like.php?api_key=368513495882&channel_url=http%3A%2F%2Fstatic.ak.fbcdn.net%2Fconnect%2Fxd_proxy.php%3Fversion%3D3%23cb%3Df13997452c%26origin%3Dhttp%253A%252F%252Fonline.wsj.com%252Ff1b037e354%26relation%3Dparent.parent%26transport%3Dpostmessage&extended_social_context=false&href=http%3A%2F%2Fonline.wsj.com%2Farticle%2FSB10001424052970204485304576640791304008536.html&layout=button_count&locale=en_US&node_type=link&ref=wsj_share_FB&sdk=joey&send=false&show_faces=false&width=90
# Ignore = Yes
#
#{+block{Facebook "like" and similar tracking URLs.}}
#www.facebook.com/(extern|plugins)/(login_status|like(box)?|activity|fan)\.php
{+block{No reason specified.} \
}
.100jq.com
